export const PLANS = [
  {
    key: "free",
    name: "Free",
    price: "$0",
    period: "forever",
    priceMonthly: null,
    priceAnnual: null,
    originalPriceMonthly: null,
    originalPriceAnnual: null,
    annualBilledNote: null,
    specs: "2 vCPU · 8 GB RAM",
    features: [
      "1 ClawTrace workspace",
      "Shared resources",
      "Community support",
    ],
    cta: "Get started free",
    highlight: false,
    paid: false,
  },
  {
    key: "starter",
    name: "Starter",
    price: "$9",
    period: "/mo",
    priceMonthly: "$9",
    priceAnnual: "$6",
    originalPriceMonthly: "$19",
    originalPriceAnnual: "$16",
    annualBilledNote: "Billed annually $72/yr",
    specs: "4 vCPU · 8 GB RAM",
    features: [
      "Standard ClawTrace workspace",
      "Persistent storage",
      "Daily backups",
      "24/7 online support",
    ],
    cta: "Get Starter",
    highlight: true,
    paid: true,
  },
  {
    key: "pro",
    name: "Pro",
    price: "$19",
    period: "/mo",
    priceMonthly: "$19",
    priceAnnual: "$14",
    originalPriceMonthly: "$29",
    originalPriceAnnual: "$24",
    annualBilledNote: "Billed annually $168/yr",
    specs: "8 vCPU · 8 GB RAM",
    features: [
      "High-performance ClawTrace workspace",
      "Persistent storage",
      "Real-time backups",
      "VIP dedicated support",
      "Custom integrations",
    ],
    cta: "Get Pro",
    highlight: false,
    paid: true,
  },
] as const;

export type Plan = (typeof PLANS)[number];
export type PlanKey = Plan["key"];
